language: crystal
sudo: required

matrix:
  include:
  - os: linux
    dist: trusty
    env: LLVM_VERSION=3.8
  - os: linux
    dist: trusty
    env: LLVM_VERSION=3.9
  - os: osx
    osx_image: xcode8.3
    env: LLVM_VERSION=3.9
  - os: osx
    osx_image: xcode8.3
    env: LLVM_VERSION=4.0
  - os: osx
    osx_image: xcode8.3
    env: LLVM_VERSION=5.0
  - os: osx
    osx_image: xcode8.3
    env: LLVM_VERSION=6.0
  - os: osx
    osx_image: xcode8.3
    env: LLVM_VERSION=7.0


before_install: |
  set -e
  set -x

  case $TRAVIS_OS_NAME in
  linux)
    sudo apt-get -qq update
    sudo apt-get install -y llvm-${LLVM_VERSION}-dev libclang-${LLVM_VERSION}-dev clang-${LLVM_VERSION}

    # FIXME: several ugly fixes since the Travis CI image is shipped
    #        with a pre-configured version of LLVM:
    #        - /usr/bin/llvm-config is configured to point to the llvm-config
    #          executable that comes with the llvm-${LLVM_VERSION} package
    #        - the $PATH env. var. is modified to use executables from /usr/bin
    #          in priority to be sure that /usr/bin/llvm-config will be used to
    #          provide llvm-config (by default, the /usr/local/clang-VERSION/bin
    #          directory is present in $PATH with a better priority)
    sudo update-alternatives --install /usr/bin/llvm-config llvm-config $(llvm-config-${LLVM_VERSION} --bindir)/llvm-config 1
    export PATH=/usr/bin:$PATH
    ;;

  osx)
    LLVM_MAJOR_VERSION=${LLVM_VERSION:0:1}
    [ $LLVM_MAJOR_VERSION -ge 4 ] && FORMULA_VERSION=$LLVM_MAJOR_VERSION || FORMULA_VERSION=$LLVM_VERSION

    brew update
    brew install llvm@$FORMULA_VERSION
    brew link --force --overwrite llvm@$FORMULA_VERSION

    # FIXME: the "libclang.dylib" shared object is manually added to the ld
    #        library path since the llvm the formula don't do it properly
    brew list --verbose ${FORMULA:-llvm@$LLVM_VERSION} | grep "\.dylib$" | xargs -n1 -I{} ln -sf {} $(brew --prefix)/lib
    ;;

  *)
    exit 1;;
  esac

  # ensure the right version of clang is used by the binding
  export CC=$(command -v clang-${LLVM_VERSION} || command -v clang-${LLVM_MAJOR_VERSION})
  $CC --version

  set +x
